### ISSUE TITLE
Throw exception if one of configurated Mappers not implement any of  Fluent Mapper Interfaces

### ISSUE THREAD

**Issue by gordinskiy** [gordinskiy/DoctrineFluentMappingBundle#18]
All mappers configured by:
```yml
doctrine_fluent:  
    mappers:  
        list:
            - Infrastructure\Doctrine\Mappers\UserMapper
            - Infrastructure\Doctrine\Mappers\RoleMapper
            - Infrastructure\Doctrine\Mappers\AccountMapper`
```
Must implement `\LaravelDoctrine\Fluent\Mapping`  or one of it inheritors.
