### ISSUE TITLE
Allow to set mapping directories path relative to the project root

### ISSUE THREAD

**Issue by gordinskiy** [gordinskiy/DoctrineFluentMappingBundle#8]
Allow to use relative path to mapping directories in configuration:
```yml
doctrine_fluent:
    mappers:
        auto_locator:
            directories:
                - 'src/Context/Infrastructure/Doctrine/Mapping'
                - 'src/SomeAnotherContext/Infrastructure/Doctrine/Mapping'
                - 'src/ActivityLog/Infrastructure/Doctrine/Mapping'
                - 'src/OneMoreContext/Infrastructure/Doctrine/Mapping'
```
instead of:
```yml
doctrine_fluent:
    mappers:
        auto_locator:
            directories:
                - '%kernel.project_dir%/src/Context/Infrastructure/Doctrine/Mapping'
                - '%kernel.project_dir%/src/SomeAnotherContext/Infrastructure/Doctrine/Mapping'
                - '%kernel.project_dir%/src/ActivityLog/Infrastructure/Doctrine/Mapping'
                - '%kernel.project_dir%/src/OneMoreContext/Infrastructure/Doctrine/Mapping'
```
