### ISSUE TITLE
Try to make configuration structure more consistent with other doctrine bundler

### ISSUE THREAD

**Issue by gordinskiy** [gordinskiy/DoctrineFluentMappingBundle#9]
Like for migration bundle
```yml
doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/App/migrations'
        'AnotherApp\Migrations': '/path/to/other/migrations'
        'SomeBundle\Migrations': '@SomeBundle/Migrations'

    # List of additional migration classes to be loaded, optional
    migrations:
        - 'App\Migrations\Version123'
        - 'App\Migrations\Version123'
```
Update configuration structure to:
```yml
doctrine_fluent:
    # List of path to search for mapping, at least one required
    mappings_paths:
        - '%kernel.project_dir%/src/App/Mappings'
        - '/path/to/other/Mappings'

    # List mapping classes to be loaded
    mappings:
        - 'App\Mappings\UserMapping'
        - 'App\Mappings\ProductMapping'
        - 'App\Mappings\OrderMapping'
```
